name: Benchmark
on:
    workflow_dispatch:

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustc --version
          cargo --version

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack --version

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: |
          deno task build --bypass-pkg-check --bypass-rs-check

      - name: Apply Patch
        run: |
          sed -i "%s/!:/:/g" pkg/si_img.d.ts

      - name: Bench
        run: |
          deno task bench
